services:
  big-ear:
    image: ghcr.io/sensority-labs/big-ear
    environment:
      DEBUG: "false"
      ETH_RPC_URL: ${ETH_RPC_URL}
      ETH_RPC_WS_URL: ${ETH_RPC_WS_URL}
      ETH_STREAM_MAX_MSGS: ${ETH_STREAM_MAX_MSGS}
      ETH_STREAM_NAME: ${ETH_STREAM_NAME}
      NATS_URL: "nats://nats:4222"
    depends_on:
      - nats
    networks:
      - sensority-labs

  vajdos:
    image: ghcr.io/sensority-labs/vajdos
    environment:
      NATS_URL: "nats://nats:4222"
      CORE_URL: "http://core:8000"
      API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}
    depends_on:
      - nats
    networks:
      - sensority-labs

  bot-builder:
    image: ghcr.io/sensority-labs/bot-builder
    environment:
      GITHUB_TOKEN: ${GITHUB_PULL_TOKEN}
      NATS_URL: "nats://nats:4222"
      NETWORK_NAME: "sensority-labs"
      PORT: 5005
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - sensority-labs

  core:
    image: ghcr.io/sensority-labs/core
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sensority_core
      WEBHOOK_URL: "http://bot-builder:5005/build"
      API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}
      GIT_SERVER_ADDRESS: ${GIT_SERVER_ADDRESS}
      DEBUG: "True"
    volumes:
      - user_home_data:/home
      - etc_data:/etc
    restart: always
    networks:
      - sensority-labs

  db:
    image: postgres:17.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensority_core
    networks:
        - sensority-labs

  nats:
    image: nats
    volumes:
      - nats:/data
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - sensority-labs

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    restart: unless-stopped
    user: root # required to read certificates
    depends_on:
      - core
    networks:
      - sensority-labs
volumes:
  db_data:
  nats:
  user_home_data:
  etc_data:

networks:
  sensority-labs:
    name: sensority-labs
